border:
  size: 20
  particle:
    color: [184, 50, 172] # RGB Value, Default is magenta
    rainbow: false # Override particle color
    rainbow-harshness: 5 # 1 = Lowest, 10 = Highest, 0 = Solid red

chatsync:
  enabled: true
  # Modes:
  # VANILLA: Uses vanilla chat format, if you write your format to use this it will work.
  # CUSTOM: Define chat formatting via this plugin, PAPI support
  # API: Handle chat formatting via the API, No chat messages will be sent if you don't handle it! (Open Ticket For "Docs")
  mode: VANILLA
  # PAPI Support
  # MiniMessage format
  # Built in placeholders (Requires Vault and Compatible Permissions Plugin): {prefix}, {player_name}, {suffix}, {server}, {message}
  custom: "<white>[<#FF0000>{server}<white>] <reset>{prefix} <white>{player_name} <dark_gray>>> <gray>{message}"

redis:
  host: "127.0.0.1"
  port: 6379
  password: "abc123"