name: AdvancedServerZones
description: The plugin that handles zone transfers and borders.
version: '${version}'
main: info.preva1l.advancedserverzones.AdvancedServerZones
api-version: '1.19'
authors: [Preva1l]

softdepend: [PlaceholderAPI, Vault]